# Generated by Django 4.1.7 on 2023-04-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='sleep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quota',
            name='study',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
