# Generated by Django 4.1.7 on 2023-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_quota_sleep_alter_quota_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='sleep',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quota',
            name='study',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
